name: Run Node.js Script

on:
  push:
    branches:
      - main

jobs:
  run-nodejs-script:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # ou a versão que você deseja usar

      # Install dependencies (se houver um package.json)
      - name: Install dependencies
        run: npm install

      # Run the script
      - name: Run script
        run: node script.js
