name: Run Node.js App

on:
  push:
    branches:
      - main  # Ou o nome do branch que você quer monitorar
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Ou a versão que você precisa

    - name: Install dependencies
      run: npm install

    - name: Run Node.js app
      run: node b.js  # Substitua pelo arquivo que deseja rodar
